name: model-training

on:
  pull_request:
    branches:
      - master

env: 
  repo_token: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  train-current:
    runs-on: ubuntu-18.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          pip install -r requirements.txt

          dvc repro train_model
          echo "### Metrics" >> report.md
          git fetch --prune
          dvc metrics diff master --targets metrics.json --old --show-md >> report.md

          echo "### Confusion matrix" >> report.md

          dvc plots diff --target confusion_matrix.csv --template confusion -x actual -y predicted --show-vega >> vega.json
          vl2png vega.json -s 1.5 | cml publish --md >> report.md
          cml-send-comment report.md
