name: model-training

on:
  push:
  pull_request:
    branches:
      - master

env: 
  repo_token: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  train-current:
    runs-on: ubuntu-18.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          pip install -r requirements.txt
          python train.py

          echo "## Current version" > report.md
          echo "### Accuracy" >> report.md
          cat accuracy.txt >> report.md

          echo "### Confusion matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md

  train-master:
    runs-on: ubuntu-18.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare master report
        run: |
          pip install -r requirements.txt
          python train.py

          echo "## Master version" > report.md
          echo "### Accuracy" >> report.md
          cat accuracy.txt >> report.md

          echo "### Confusion matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md

