name: model-training

on:
  pull_request:
    branches:
      - master

env: 
  repo_token: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  train-current:
    runs-on: ubuntu-18.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          apt-get update 
          apt-get install jq
          pip install -r requirements.txt

          dvc repro train_model

          echo "### Accuracy" >> report.md
          dvc metrics diff master --tragets metrics.json --old --show-md >> report.md

          echo "### Confusion matrix" >> report.md
          dvc plots diff --targets master --template confusion -x actual -y predicted --show-vega >> vega.json
          vl2png vega.json --md >> report.md
          cml-send-comment report.md
