name: model-training

on:
  pull_request:
    branches:
      - master

env: 
  repo_token: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  train-current:
    runs-on: ubuntu-18.04
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          pip install -r requirements.txt
          dvc repro train_model

          echo "### Accuracy" >> report.md
          dvc metrics diff --target metrics.json --old --show-md >> repor.md

          echo "### Confusion matrix" >> report.md
          dvc plots diff --targets confusion_matrix.csv -- master dvc --show-vega -x actual -y predicted >> vega.json

          vl2png vega.json -s 1.5 | cml-publish --md >> report.md
          cml-send-comment report.md
